var input = document.querySelector('.Input')
var AddBTN = document.querySelector('.AddBTN')
var ClearBTN = document.querySelector('.ClearBTN')
var Town = document.querySelector('.Town')
var Output = document.querySelector('.Output')
var input = document.querySelector('.Input')
